development:
  adapter: postgresql
  database: wInevitable_development
  host: localhost
  username: CaptainAmerica

test:
  adapter: postgresql
  encoding: unicode
  database: wInevitable_test
  pool: 5
  username: CaptainAmerica